# Generated by Django 4.2.28 on 2026-02-16 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('GK', 'Воротар'), ('DEF', 'Захисник'), ('MID', 'Півзахисник'), ('FWD', 'Нападник')], max_length=20)),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('matches_played', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Гравець',
                'verbose_name_plural': 'Гравці',
                'ordering': ['-overall_rating'],
            },
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('minutes_played', models.IntegerField(default=90)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='my_app.player')),
            ],
            options={
                'verbose_name': 'Статистика гравця',
                'verbose_name_plural': 'Статистика гравців',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerRatingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_history', to='my_app.player')),
            ],
            options={
                'verbose_name': 'Історія рейтингу',
                'verbose_name_plural': 'Історія рейтингів',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
