# Generated by Django 4.2.28 on 2026-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, help_text='Ігровий номер (1-99)', null=True),
        ),
    ]
