# Generated by Django 4.2.28 on 2026-02-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_player_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UPLSquadCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True, verbose_name='Назва команди')),
                ('api_team_id', models.IntegerField(verbose_name='ID команди в API')),
                ('squad_json', models.JSONField(default=list, verbose_name='Склад (JSON)')),
                ('fetched_at', models.DateTimeField(verbose_name='Час оновлення')),
            ],
            options={
                'verbose_name': 'Кеш складу УПЛ',
                'verbose_name_plural': 'Кеш складів УПЛ',
            },
        ),
    ]
