# Generated by Django 4.2.28 on 2026-02-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_upl_squad_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerstats',
            name='interceptions',
            field=models.IntegerField(default=0, help_text='Перехоплення'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='key_passes',
            field=models.IntegerField(default=0, help_text='Ключові передачі (передача під удар)'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='saves',
            field=models.IntegerField(default=0, help_text='Сейви (тільки для воротаря)'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='shots',
            field=models.IntegerField(default=0, help_text='Усього ударів по воротах'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='shots_on_target',
            field=models.IntegerField(default=0, help_text='Удари у ціль (xG proxy)'),
        ),
        migrations.AddField(
            model_name='playerstats',
            name='tackles',
            field=models.IntegerField(default=0, help_text='Відбори мяча'),
        ),
    ]
