# Generated by Django 4.2.28 on 2026-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_tournament_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус заявки'),
        ),
    ]
